version: "3.4"
services:
  mongo:
    restart: unless-stopped
    image: mongo:4.4.3
    command: ["--replSet", "rs0", "--bind_ip_all"]
    hostname: mongo
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    ports:
      - 27020:27017
    volumes:
      - /tmp/video-chat/db:/data/db

  rabbit:
    image: rabbitmq:3.7.18-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=editor
      - RABBITMQ_DEFAULT_PASS=Qwerty12345!
      - RABBIT_HOST=rabbit:5672

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass Qwerty12345!
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - 6379:6379